### ISSUE TITLE
Request for the code of IAMM large

### ISSUE THREAD

**Issue by xhrt** [zhouzhouyang520/IAMM#5]
Does this code include the code of IAMM large?If not,could you please offer me the code of IAMM large.

**Comment by zhouzhouyang520** [comment]
This code does not include IAMM large. Since this portion of our code is not yet organized, it has not been uploaded. For your convenience, we have created a new repository "IAMM_large" (containing unorganized code, https://github.com/zhouzhouyang520/IAMM_large.git).

To use this model, follow these steps:

1. cd GLM3_IAMN_keywords2V2/examples
2. sh run.sh
3. Results will be saved in either ./out.log or ./output/output_ed_sit/ed_result.txt


Additionally, we discovered that the main code only supports ChatGLM models. For broader compatibility, we have created another repository called "ED_Llama_V2"(https://github.com/zhouzhouyang520/ED_Llama_baseV2.git). This branch supports multiple models including: ChatGLM、Llama 3.1、Gemma、and other models. The steps remain the same as described above.

**Comment by Fang-git0** [comment]
The content of the glmtuner folder seems incomplete, and I couldn't find the run_sft function. Is it incomplete?

`
Traceback (most recent call last):
  File "../src/train_bash.py", line 1, in <module>
    from glmtuner.tuner import get_train_args, run_sft, run_rm, run_ppo
ImportError: cannot import name 'get_train_args' from 'glmtuner.tuner' (unknown location)
Traceback (most recent call last):
  File "../src/train_bash.py", line 1, in <module>
    from glmtuner.tuner import get_train_args, run_sft, run_rm, run_ppo
ImportError: cannot import name 'get_train_args' from 'glmtuner.tuner' (unknown location)
`
